## Activity 01: Use NumPy to compute the Mean, Median, and Variance

In this activity, you will consolidate the skills you've acquired in the last exercise and use NumPy to do some very basic mathematical calculations on our `normal_distribution` dataset.   
NumPy has a consistent API, so it should be rather easy to transfer your knowledge of the mean method to median and variance. 

#### Loading the dataset

In [1]:
# importing the necessary dependencies
import numpy as np

In [2]:
# loading the Dataset
dataset = np.genfromtxt('./data/normal_distribution.csv', delimiter=',')

dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.7476749

In [3]:
# looking at the first two rows of the dataset
dataset[:2]

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942]])

#### Mean

In [4]:
# calculate the mean of the third row
dataset[3].mean()

100.56785907

In [5]:
# calculate the mean of the last column
dataset[:, -1].mean()

100.4404927375

In [6]:
# calculate the mean of the intersection of the first 3 rows and first 3 columns
dataset[:3, :3].mean()

97.87197312333333

---

#### Median

In [17]:
# calculate the median of the last row
np.median(dataset[-1])

99.18748092

In [32]:
# calculate the median of the last 3 columns
np.median(dataset[:, -3:])

99.47332349999999

In [37]:
# calculate the median of each row

np.median(dataset, axis=1)

array([ 98.77910163,  97.17512034,  98.58782879, 100.68449836,
       101.00170737,  97.76908825, 101.85002253, 100.04756697,
       102.24292555,  99.59514997, 100.4955753 ,  99.8860714 ,
        99.00647994,  98.67276177, 102.44376222,  96.61933565,
       104.0968893 , 100.72023043,  98.70877396,  99.75008654,
       104.89344428, 101.00634942,  98.30543801,  99.18748092])

In [38]:
# calculate the median of each row
[np.median(data) for data in dataset]

[98.77910163,
 97.17512034,
 98.58782879,
 100.684498365,
 101.001707375,
 97.76908825,
 101.85002253,
 100.04756696999999,
 102.242925555,
 99.59514997,
 100.49557530499999,
 99.886071405,
 99.006479935,
 98.672761775,
 102.44376222,
 96.61933565499999,
 104.0968893,
 100.72023042500001,
 98.70877396,
 99.75008653500001,
 104.89344427500001,
 101.006349425,
 98.305438015,
 99.18748092]

---

#### Variance

In [45]:
# calculate the variance of each column
np.var(dataset, axis=0)

array([23.64757465, 29.78886109, 20.50542011, 26.03204443, 28.38853175,
       19.09960817, 17.67291174, 16.17923204])

In [46]:
dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.7476749

In [60]:
# calculate the variance of the intersection of the last 2 rows and first 2 columns
np.var(dataset[-2:, -2:])

9.875475447273148

The values of the variance might seem a little bit strange at first.   
You can always go back to the topic that gives you a quick statistical overview to recap what you've learned so far.   

> **Note:**   
Just remember, the variance is not the standard deviation.   

Try calculation the standard deviation with NumPy to get a more descriptive value when comparing it to our dataset

In [33]:
# calculate the standard deviation for the dataset
np.std(dataset)

4.838197554269257